name: Deploy Cloud Functions
on:
  push:
    branches:
      - "main"
    
jobs:
  Deploy1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
    - id: "deploy"
      uses: "google-github-actions/deploy-cloud-functions@v2"
      with:
        name: "processing" 
        runtime: "python310"
        region: us-central1
        description: function trigger
        entry_point: main
        source_dir: ./src/processing
        ingress_settings: ALLOW_ALL

  # Deploy2:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - id: "auth"
  #     uses: "google-github-actions/auth@v2"
  #     with:
  #       credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
  #   - id: "deploy"
  #     uses: "google-github-actions/deploy-cloud-functions@v2"
  #     with:
  #       name: "response" 
  #       runtime: "python310"
  #       region: us-central1
  #       description: function trigger
  #       entry_point: main
  #       source_dir: ./src/response
  #       ingress_settings: ALLOW_ALL